import type {
  AdminMember,
  AuditLogEntry,
  CategorySkillMapping,
  ExtendedMaintenanceRequest,
  QueueItem,
  SkillDefinition,
  SLAPolicy,
  StaffMember,
  UnitStructure,
} from "../types/operations";

export const INITIAL_STAFF_MEMBERS: StaffMember[] = [
  {
    id: "CH-ST-001",
    name: "Sipho",
    surname: "Mhlongo",
    email: "sipho.mhlongo@corridorhills.tut.ac.za",
    phone: "+27 82 451 9021",
    roleTitle: "Electrical Specialist",
    skills: ["electrical", "general"],
    status: "AVAILABLE",
    active: true,
    activeJobsCount: 1,
    completedTodayCount: 3,
    shiftHours: "07:30 — 16:30",
  },
  {
    id: "CH-ST-002",
    name: "David",
    surname: "Khumalo",
    email: "david.khumalo@corridorhills.tut.ac.za",
    phone: "+27 73 892 1104",
    roleTitle: "Plumbing Specialist",
    skills: ["plumbing", "general"],
    status: "BUSY",
    active: true,
    activeJobsCount: 2,
    completedTodayCount: 2,
    shiftHours: "08:00 — 17:00",
  },
  {
    id: "CH-ST-003",
    name: "Thabo",
    surname: "Ndlovu",
    email: "thabo.ndlovu@corridorhills.tut.ac.za",
    phone: "+27 84 312 8790",
    roleTitle: "General Maintenance Artisan",
    skills: ["general", "carpentry", "access_control"],
    status: "AVAILABLE",
    active: true,
    activeJobsCount: 1,
    completedTodayCount: 1,
    shiftHours: "07:00 — 16:00",
  },
  {
    id: "CH-ST-004",
    name: "Nomsa",
    surname: "Zulu",
    email: "nomsa.zulu@corridorhills.tut.ac.za",
    phone: "+27 79 654 3210",
    roleTitle: "Senior Facilities Specialist",
    skills: ["electrical", "plumbing", "general", "hvac"],
    status: "ON_BREAK",
    active: true,
    activeJobsCount: 0,
    completedTodayCount: 4,
    shiftHours: "06:30 — 15:30",
  },
];

export const INITIAL_ADMIN_MEMBERS: AdminMember[] = [
  {
    id: "CH-ADM-001",
    name: "Lerato",
    surname: "Molefe",
    email: "lerato.molefe@corridorhills.tut.ac.za",
    roleTitle: "Residence Operations Lead",
    permissions: [
      "requests:read",
      "requests:write",
      "requests:reassign",
      "staff:manage",
      "residents:import",
      "units:manage",
      "analytics:read",
      "config:manage",
      "audit:read",
    ],
  },
  {
    id: "CH-ADM-002",
    name: "Katlego",
    surname: "Dlamini",
    email: "katlego.dlamini@corridorhills.tut.ac.za",
    roleTitle: "Facilities Dispatch Supervisor",
    permissions: [
      "requests:read",
      "requests:write",
      "requests:reassign",
      "staff:view",
      "units:read",
      "analytics:read",
      "audit:read",
    ],
  },
];

export const INITIAL_SKILLS: SkillDefinition[] = [
  {
    id: "electrical",
    name: "Electrical",
    description:
      "Power plugs, switches, light fixtures, stoves, distribution boards, wiring faults",
    active: true,
  },
  {
    id: "plumbing",
    name: "Plumbing",
    description: "Taps, sinks, showers, toilets, geysers, pipe blockages, pressure valves",
    active: true,
  },
  {
    id: "general",
    name: "General Maintenance",
    description: "Furniture, doors, locks, curtains, blinds, minor physical structural repairs",
    active: true,
  },
  {
    id: "carpentry",
    name: "Carpentry & Joinery",
    description: "Beds, study desks, wardrobes, hinges, door frames",
    active: true,
  },
  {
    id: "access_control",
    name: "Access Control & Security",
    description: "Keycard readers, digital deadbolts, security gate latches",
    active: true,
  },
  {
    id: "hvac",
    name: "Ventilation & Extraction",
    description: "Kitchen extraction vents, bathroom fans, air circulation units",
    active: true,
  },
];

export const INITIAL_SLA_POLICIES: Record<string, SLAPolicy> = {
  emergency: {
    priority: "emergency",
    targetHours: 1,
    escalationHours: 0.5,
    description:
      "Immediate hazard (exposed sparks, burst water pipe, security door breach). Dispatch immediately.",
  },
  high: {
    priority: "high",
    targetHours: 2,
    escalationHours: 1.5,
    description:
      "Essential facility outage affecting room or unit functionality. Target under 2 hours.",
  },
  standard: {
    priority: "standard",
    targetHours: 24,
    escalationHours: 18,
    description: "Routine maintenance without immediate security or health impact.",
  },
  low: {
    priority: "low",
    targetHours: 48,
    escalationHours: 36,
    description: "Cosmetic or minor convenience request.",
  },
};

export const INITIAL_CATEGORY_SKILL_MAPPINGS: CategorySkillMapping[] = [
  {
    category: "Electrical",
    issueType: "Stove / Hot plate",
    requiredSkill: "electrical",
    defaultPriority: "high",
    safetyRisk: false,
    waterElectricityImpact: true,
  },
  {
    category: "Electrical",
    issueType: "Power socket / plug sparking",
    requiredSkill: "electrical",
    defaultPriority: "emergency",
    safetyRisk: true,
    waterElectricityImpact: true,
  },
  {
    category: "Electrical",
    issueType: "Room light not working",
    requiredSkill: "electrical",
    defaultPriority: "standard",
    safetyRisk: false,
    waterElectricityImpact: false,
  },
  {
    category: "Plumbing",
    issueType: "Tap / Faucet leak",
    requiredSkill: "plumbing",
    defaultPriority: "standard",
    safetyRisk: false,
    waterElectricityImpact: true,
  },
  {
    category: "Plumbing",
    issueType: "Burst pipe / major flood",
    requiredSkill: "plumbing",
    defaultPriority: "emergency",
    safetyRisk: true,
    waterElectricityImpact: true,
  },
  {
    category: "Plumbing",
    issueType: "Blocked toilet",
    requiredSkill: "plumbing",
    defaultPriority: "high",
    safetyRisk: true,
    waterElectricityImpact: true,
  },
  {
    category: "Plumbing",
    issueType: "Shower drain blockage",
    requiredSkill: "plumbing",
    defaultPriority: "standard",
    safetyRisk: false,
    waterElectricityImpact: false,
  },
  {
    category: "Furniture",
    issueType: "Bed frame damaged / collapsed",
    requiredSkill: "general",
    defaultPriority: "high",
    safetyRisk: false,
    waterElectricityImpact: false,
  },
  {
    category: "Blinds / Curtains",
    issueType: "Broken blind cord / mechanism",
    requiredSkill: "general",
    defaultPriority: "low",
    safetyRisk: false,
    waterElectricityImpact: false,
  },
  {
    category: "Doors / Locks",
    issueType: "Room lock broken / cannot lock",
    requiredSkill: "general",
    defaultPriority: "emergency",
    safetyRisk: true,
    waterElectricityImpact: false,
  },
];

export const INITIAL_UNITS: UnitStructure[] = [
  {
    id: "F301",
    block: "F",
    floor: 3,
    unitNumber: "301",
    rooms: ["A", "B", "C"],
    occupancy: 6,
    maxOccupancy: 6,
    students: [
      {
        studentNumber: "220123456",
        name: "Sibusiso",
        surname: "Khoza",
        room: "C",
        residenceStatus: "Active",
      },
      {
        studentNumber: "220184719",
        name: "Dumisani",
        surname: "Mthembu",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "221503942",
        name: "Lwandle",
        surname: "Cele",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "219804561",
        name: "Bongani",
        surname: "Radebe",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "222394851",
        name: "Kagiso",
        surname: "Modise",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "218765432",
        name: "Nhlanhla",
        surname: " Sithole",
        room: "C",
        residenceStatus: "Active",
      },
    ],
    openIssuesCount: 2,
    urgentIssuesCount: 1,
    lastMaintenanceDate: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    recurringAlert: true,
    recurringAlertReason: "2 stove plate issues logged in F301 within 14 days",
  },
  {
    id: "F302",
    block: "F",
    floor: 3,
    unitNumber: "302",
    rooms: ["A", "B", "C"],
    occupancy: 6,
    maxOccupancy: 6,
    students: [
      {
        studentNumber: "223001122",
        name: "Thandeka",
        surname: "Mabaso",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "223001123",
        name: "Zanele",
        surname: "Nene",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "223001124",
        name: "Precious",
        surname: "Moyo",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "223001125",
        name: "Andile",
        surname: "Ndlovu",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "223001126",
        name: "Mpumelelo",
        surname: "Sibanda",
        room: "C",
        residenceStatus: "Active",
      },
      {
        studentNumber: "223001127",
        name: "Vuyo",
        surname: "Nkosi",
        room: "C",
        residenceStatus: "Active",
      },
    ],
    openIssuesCount: 0,
    urgentIssuesCount: 0,
    lastMaintenanceDate: new Date(Date.now() - 7 * 86400 * 1000).toISOString(),
  },
  {
    id: "F201",
    block: "F",
    floor: 2,
    unitNumber: "201",
    rooms: ["A", "B", "C"],
    occupancy: 6,
    maxOccupancy: 6,
    students: [
      {
        studentNumber: "221445566",
        name: "Tshepo",
        surname: "Mahlangu",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "221445567",
        name: "Karabo",
        surname: "Mokoena",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "221445568",
        name: "Siyabonga",
        surname: "Zondi",
        room: "C",
        residenceStatus: "Active",
      },
    ],
    openIssuesCount: 1,
    urgentIssuesCount: 0,
    lastMaintenanceDate: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
  },
  {
    id: "A101",
    block: "A",
    floor: 1,
    unitNumber: "101",
    rooms: ["A", "B", "C"],
    occupancy: 6,
    maxOccupancy: 6,
    students: [
      {
        studentNumber: "222119988",
        name: "Mpho",
        surname: "Ramaphosa",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "222119989",
        name: "Lesego",
        surname: "Tau",
        room: "B",
        residenceStatus: "Active",
      },
      {
        studentNumber: "222119990",
        name: "Nthabiseng",
        surname: "Phiri",
        room: "C",
        residenceStatus: "Active",
      },
    ],
    openIssuesCount: 1,
    urgentIssuesCount: 1,
    lastMaintenanceDate: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    recurringAlert: false,
  },
  {
    id: "B204",
    block: "B",
    floor: 2,
    unitNumber: "204",
    rooms: ["A", "B", "C"],
    occupancy: 6,
    maxOccupancy: 6,
    students: [
      {
        studentNumber: "220998877",
        name: "Tebogo",
        surname: "Baloyi",
        room: "A",
        residenceStatus: "Active",
      },
      {
        studentNumber: "220998878",
        name: "Ofentse",
        surname: "Mashaba",
        room: "B",
        residenceStatus: "Active",
      },
    ],
    openIssuesCount: 0,
    urgentIssuesCount: 0,
    lastMaintenanceDate: new Date(Date.now() - 12 * 86400 * 1000).toISOString(),
  },
];

export const INITIAL_EXTENDED_REQUESTS: ExtendedMaintenanceRequest[] = [
  {
    id: "CH-2026-001042",
    idempotencyKey: "seed-key-1042",
    studentNumber: "220123456",
    unit: "F301",
    room: "C",
    location: "F301C",
    area: "Kitchen",
    category: "Electrical",
    issueType: "Stove / Hot plate",
    description:
      "The front-left stove plate is not heating up. When turning the dial, the indicator light does not turn on.",
    attachments: [
      {
        id: "att-1",
        name: "stove_plate.jpg",
        size: 1024 * 780,
        type: "image/jpeg",
        url: "/images/A.jpg",
        uploadedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      },
    ],
    status: "in_progress",
    urgency: "standard",
    operationalPriority: "high",
    requiredSkill: "electrical",
    assignedStaffId: "CH-ST-001",
    assignedStaffName: "Sipho Mhlongo",
    assignedTechnician: {
      name: "Sipho Mhlongo",
      specialty: "Electrical Specialist",
      isQueued: false,
    },
    sla: {
      targetHours: 2,
      dueAt: new Date(Date.now() - 2 * 3600 * 1000 + 2 * 3600 * 1000).toISOString(),
      slaStatus: "on_track",
    },
    timestamps: {
      reported_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      triaged_at: new Date(Date.now() - 3.8 * 3600 * 1000).toISOString(),
      assigned_at: new Date(Date.now() - 3.7 * 3600 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
      started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    history: [
      {
        id: "hist-1042-1",
        status: "submitted",
        title: "Report Submitted",
        description: "Student logged electrical stove fault.",
        timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        actor: "Resident (220123456)",
      },
      {
        id: "hist-1042-2",
        status: "assigned",
        title: "Automated Dispatch to Sipho Mhlongo",
        description:
          "Assigned via Electrical Queue algorithm based on technician availability and location priority.",
        timestamp: new Date(Date.now() - 3.7 * 3600 * 1000).toISOString(),
        actor: "Assignment Engine",
      },
      {
        id: "hist-1042-3",
        status: "accepted",
        title: "Job Accepted by Sipho Mhlongo",
        description: "Technician reviewed work order and accepted task.",
        timestamp: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
        actor: "Sipho Mhlongo (CH-ST-001)",
      },
      {
        id: "hist-1042-4",
        status: "in_progress",
        title: "Technician Commenced Work",
        description:
          "Inspection of heating element wiring and circuit breaker started in F301 kitchen.",
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        actor: "Sipho Mhlongo (CH-ST-001)",
      },
    ],
    technicianNotes: [
      {
        id: "tn-1",
        author: "Sipho Mhlongo",
        note: "Tested continuity with multimeter; heating coil element has open circuit. Replacing with standard 150mm Defy solid spiral plate.",
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    workEvidence: [
      {
        id: "we-1",
        type: "before",
        name: "stove_coils_precheck.jpg",
        url: "/images/h.jpg",
        uploadedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        uploadedByStaffId: "CH-ST-001",
      },
    ],
    recurringDetected: true,
    recurringNote: "2 stove electrical issues logged in F301 within 14 days",
  },
  {
    id: "CH-2026-001048",
    idempotencyKey: "seed-key-1048",
    studentNumber: "220184719",
    unit: "F301",
    room: "A",
    location: "F301A",
    area: "My Room",
    category: "Electrical",
    issueType: "Power socket / plug sparking",
    description:
      "The double power outlet next to my study desk gives a visible blue spark when inserting my laptop plug.",
    attachments: [],
    status: "assigned",
    urgency: "emergency",
    operationalPriority: "emergency",
    requiredSkill: "electrical",
    assignedStaffId: "CH-ST-001",
    assignedStaffName: "Sipho Mhlongo",
    assignedTechnician: {
      name: "Sipho Mhlongo",
      specialty: "Electrical Specialist",
      isQueued: false,
    },
    sla: {
      targetHours: 1,
      dueAt: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
      slaStatus: "at_risk",
    },
    timestamps: {
      reported_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      assigned_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    history: [
      {
        id: "hist-1048-1",
        status: "submitted",
        title: "Emergency Issue Submitted",
        description: "Resident reported sparking wall socket.",
        timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
        actor: "Resident (220184719)",
      },
      {
        id: "hist-1048-2",
        status: "assigned",
        title: "Dispatched to Sipho Mhlongo",
        description:
          "Classified as Emergency Priority. Sent directly to on-site Electrical technician.",
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        actor: "Assignment Engine",
      },
    ],
  },
  {
    id: "CH-2026-000984",
    idempotencyKey: "seed-key-0984",
    studentNumber: "220123456",
    unit: "F301",
    room: "C",
    location: "F301C",
    area: "Bathroom 1",
    category: "Plumbing",
    issueType: "Tap / Faucet leak",
    description:
      "Cold water tap in Bathroom 1 basin is constantly dripping and won't turn off firmly.",
    attachments: [],
    status: "resolved",
    urgency: "standard",
    operationalPriority: "standard",
    requiredSkill: "plumbing",
    assignedStaffId: "CH-ST-002",
    assignedStaffName: "David Khumalo",
    assignedTechnician: {
      name: "David Khumalo",
      specialty: "Plumbing Specialist",
      isQueued: false,
    },
    sla: {
      targetHours: 24,
      dueAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      slaStatus: "on_track",
    },
    timestamps: {
      reported_at: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
      triaged_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      assigned_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
      started_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
      resolved_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    },
    resolutionSummary:
      "Replaced 15mm ceramic tap washer, tightened spindle, and flushed tap seating. No more leak observed.",
    resolvedPhotoUrl: "/images/w.jpg",
    history: [
      {
        id: "hist-0984-1",
        status: "submitted",
        title: "Report Submitted",
        description: "Cold tap leak reported.",
        timestamp: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
        actor: "Resident (220123456)",
      },
      {
        id: "hist-0984-2",
        status: "assigned",
        title: "Assigned to David Khumalo",
        description: "Assigned via plumbing queue.",
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        actor: "Assignment Engine",
      },
      {
        id: "hist-0984-3",
        status: "resolved",
        title: "Maintenance Marked Resolved",
        description: "New ceramic tap washer installed and tested.",
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        actor: "David Khumalo (CH-ST-002)",
      },
    ],
  },
  {
    id: "CH-2026-001105",
    idempotencyKey: "seed-key-1105",
    studentNumber: "220123456",
    unit: "F301",
    room: "C",
    location: "F301C",
    area: "My Room",
    category: "Blinds / Curtains",
    issueType: "Broken blind cord / mechanism",
    description:
      "The pull cord snapped on the window blinds, so the blinds are stuck halfway down.",
    attachments: [],
    status: "submitted",
    urgency: "low",
    operationalPriority: "low",
    requiredSkill: "general",
    sla: {
      targetHours: 48,
      dueAt: new Date(Date.now() + 47 * 3600 * 1000).toISOString(),
      slaStatus: "on_track",
    },
    timestamps: {
      reported_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    history: [
      {
        id: "hist-1105-1",
        status: "submitted",
        title: "Report Submitted",
        description: "Ticket logged. Awaiting general maintenance allocation.",
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        actor: "Resident (220123456)",
      },
    ],
    queuePosition: 1,
  },
  {
    id: "CH-2026-000891",
    idempotencyKey: "seed-key-0891",
    studentNumber: "222119988",
    unit: "A101",
    room: "A",
    location: "A101A",
    area: "My Room",
    category: "Doors / Locks",
    issueType: "Room lock broken / cannot lock",
    description:
      "Deadbolt lock cylinder is spinning freely from outside. Resident cannot lock door when leaving for TUT campus classes.",
    attachments: [],
    status: "assigned",
    urgency: "high",
    operationalPriority: "emergency",
    requiredSkill: "general",
    assignedStaffId: "CH-ST-003",
    assignedStaffName: "Thabo Ndlovu",
    assignedTechnician: {
      name: "Thabo Ndlovu",
      specialty: "General Maintenance",
      isQueued: false,
    },
    sla: {
      targetHours: 1,
      dueAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      slaStatus: "breached",
      breachedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    timestamps: {
      reported_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
      assigned_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    },
    history: [
      {
        id: "hist-0891-1",
        status: "submitted",
        title: "Lock Fault Submitted",
        description: "Security risk: door cannot lock.",
        timestamp: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
        actor: "Resident (222119988)",
      },
      {
        id: "hist-0891-2",
        status: "assigned",
        title: "Assigned to Thabo Ndlovu",
        description: "General artisan assigned for cylinder overhaul.",
        timestamp: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
        actor: "Assignment Engine",
      },
    ],
  },
];

export const INITIAL_QUEUES: QueueItem[] = [
  {
    id: "q-item-1",
    queueId: "queue-general",
    skill: "general",
    requestId: "CH-2026-001105",
    priority: "low",
    queuedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    effectiveScore: 120,
    reason: "Awaiting next general technician shift cycle",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-001",
    timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    actorId: "220123456",
    actorName: "Sibusiso Khoza",
    actorRole: "STUDENT",
    action: "REQUEST_SUBMITTED",
    targetType: "request",
    targetId: "CH-2026-001042",
    newValue: "submitted",
    reason: "Initial student report for broken stove plate",
  },
  {
    id: "aud-002",
    timestamp: new Date(Date.now() - 3.7 * 3600 * 1000).toISOString(),
    actorId: "SYSTEM",
    actorName: "Automated Assignment Engine",
    actorRole: "ADMIN",
    action: "REQUEST_AUTO_ASSIGNED",
    targetType: "request",
    targetId: "CH-2026-001042",
    previousValue: "unassigned",
    newValue: "CH-ST-001 (Sipho Mhlongo)",
    reason: "Matched skill: electrical, status: AVAILABLE",
  },
  {
    id: "aud-003",
    timestamp: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    actorId: "CH-ST-001",
    actorName: "Sipho Mhlongo",
    actorRole: "STAFF",
    action: "JOB_ACCEPTED",
    targetType: "request",
    targetId: "CH-2026-001042",
    previousValue: "assigned",
    newValue: "accepted",
  },
  {
    id: "aud-004",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    actorId: "CH-ST-001",
    actorName: "Sipho Mhlongo",
    actorRole: "STAFF",
    action: "WORK_STARTED",
    targetType: "request",
    targetId: "CH-2026-001042",
    previousValue: "accepted",
    newValue: "in_progress",
    reason: "Technician arrived at unit F301",
  },
  {
    id: "aud-005",
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    actorId: "SYSTEM",
    actorName: "Assignment Engine",
    actorRole: "ADMIN",
    action: "EMERGENCY_DISPATCH",
    targetType: "request",
    targetId: "CH-2026-001048",
    newValue: "CH-ST-001",
    reason: "Sparking outlet safety risk requires immediate electrical intervention",
  },
];
